### ISSUE TITLE
[Bug]An exception will be thrown when the input file type does not match the expectation.

### ISSUE THREAD

**Issue by Initial-heart-1** [allenfrostline/pyNCMDUMP#5] opened 2022-10-04 09:41 UTC
The problem came with the new version, when I passed in a folder where pyNCMDUMP had already been executed as in the previous version, it threw an AssertionError, at ncmdump.py L60.

```
assert binascii.b2a_hex(header) == b'4354454e4644414d'
```

This line of code is very well understood and is used to confirm that the input file is as expected. It does not have any problems.

In previous versions, pyNCMDUMP would filter `*.ncm` file as input. Now, pyNCMDUMP does not do this.

**Comment by Initial-heart-1** [comment] 2022-10-04 09:51
为什么不提交一个 Pull Request？因为今天已经是国庆假期的第 4 天了！从第一天开始我一直在 Github 上活跃 ~~，这实在是不像一个摸鱼怪，所以我宣布我摸了！~~

**Comment by allenfrostline** [comment] 2022-10-04 12:12
Fixed in https://github.com/allenfrostline/pyNCMDUMP/commit/25e23a7437ba185a7d4991fa6d78bf9bc46a03b0. Also imo the error was not because of running ncmdump multiple times (in which case the file should be skipped explicitly), but that there's corrupted output.

**Closed by allenfrostline** 2022-10-04 12:12 UTC

**Comment by Initial-heart-1** [comment] 2022-10-04 13:07
Okay, I went back and consulted the code. Whether or not a file is skipped is determined by its suffix, and when it enters the decryption process, it means that the incoming file passed the suffix check. The suffix of the file apparently has nothing to do with whether the file is corrupt or not. I then checked the incoming file. It was fine.






------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年10月4日(星期二) 晚上8:12
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [allenfrostline/pyNCMDUMP] [Bug]An exception will be thrown when the input file type does not match the expectation. (Issue #5)





 
Fixed in 25e23a7. Also imo the error was not because of running ncmdump multiple times (in which case the file should be skipped explicitly), but that there's corrupted output.

**Comment by allenfrostline** [comment] 2022-10-04 13:15
Yes the original push I made yesterday was skipping based on whether output file (.mp3 or .flac) exists already. That means if there’s a file that’s not ending with .ncm, the script would still try to convert it. This broke my local tests a few times as files without suffix were created when conversion is aborted. In the latest commit I added explicitly the suffix check on input file so that should be fixed now.

Can you pull the latest commit and test again. If bug still persist please copy the example here so I can reproduce in my setting. 🙂

**Comment by Initial-heart-1** [comment] 2022-10-04 13:20
> Yes the original push I made yesterday was skipping based on whether output file (.mp3 or .flac) exists already. That means if there’s a file that’s not ending with .ncm, the script would still try to convert it. This broke my local tests a few times as files without suffix were created when conversion is aborted. In the latest commit I added explicitly the suffix check on input file so that should be fixed now.
> 
> Can you pull the latest commit and test again. If bug still persist please copy the example here so I can reproduce in my setting. 🙂

Yes, this has been fixed in the latest commit, and the reply above is for "but that there's corrupted output".
